import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import {startDaemon} from '../src/daemon/server.js';
import {generateTypeScriptFromBase} from '../dist/client/generator.js';
import {mockBase} from './fixtures/mock-base.js';

const code = generateTypeScriptFromBase(mockBase);

async function withDaemon(run) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'airgen-daemon-test-'));
  const outPath = path.join(dir, 'airtable-schema.ts');
  const logs = [];
  const server = await startDaemon({port: 0, outPath, log: message => logs.push(message)});
  const {port} = server.address();
  const url = `http://127.0.0.1:${port}`;
  try {
    await run({url, outPath, dir, logs});
  } finally {
    server.close();
    fs.rmSync(dir, {recursive: true, force: true});
  }
}

function postSchema(url, body) {
  return fetch(`${url}/save-schema`, {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify(body),
  });
}

test('GET /health returns 204 with CORS headers', async () => {
  await withDaemon(async ({url}) => {
    const response = await fetch(`${url}/health`);
    assert.equal(response.status, 204);
    assert.equal(response.headers.get('access-control-allow-origin'), '*');
  });
});

test('OPTIONS preflight is answered', async () => {
  await withDaemon(async ({url}) => {
    const response = await fetch(`${url}/save-schema`, {method: 'OPTIONS'});
    assert.equal(response.status, 204);
    assert.equal(response.headers.get('access-control-allow-origin'), '*');
    assert.match(response.headers.get('access-control-allow-methods'), /POST/);
  });
});

test('valid payload is written to the configured path', async () => {
  await withDaemon(async ({url, outPath}) => {
    const response = await postSchema(url, {code, signature: 'abc', tableCount: 4});
    assert.equal(response.status, 200);
    assert.deepEqual(await response.json(), {ok: true, written: true});
    assert.equal(fs.readFileSync(outPath, 'utf8'), code);
  });
});

test('identical payload skips the write', async () => {
  await withDaemon(async ({url, logs}) => {
    await postSchema(url, {code});
    const response = await postSchema(url, {code});
    assert.deepEqual(await response.json(), {ok: true, written: false});
    assert.ok(logs.some(line => line.includes('unchanged')));
  });
});

test('client-supplied filePath is ignored', async () => {
  await withDaemon(async ({url, outPath, dir}) => {
    const hijackPath = path.join(dir, 'hijacked.txt');
    const response = await postSchema(url, {code, filePath: hijackPath});
    assert.equal(response.status, 200);
    assert.ok(fs.existsSync(outPath));
    assert.ok(!fs.existsSync(hijackPath));
  });
});

test('payload without the airgen header is rejected and nothing is written', async () => {
  await withDaemon(async ({url, outPath}) => {
    const response = await postSchema(url, {code: 'console.log("malicious")'});
    assert.equal(response.status, 400);
    assert.ok(!fs.existsSync(outPath));
  });
});

test('non-JSON and non-string payloads are rejected', async () => {
  await withDaemon(async ({url, outPath}) => {
    const bad = await fetch(`${url}/save-schema`, {method: 'POST', body: 'not json'});
    assert.equal(bad.status, 400);
    const wrongType = await postSchema(url, {code: 42});
    assert.equal(wrongType.status, 400);
    assert.ok(!fs.existsSync(outPath));
  });
});

test('oversized payload is rejected', async () => {
  await withDaemon(async ({url, outPath}) => {
    const huge = '// Generated by airgen — do not edit.\n' + 'x'.repeat(2 * 1024 * 1024 + 1);
    const response = await postSchema(url, {code: huge}).catch(() => null);
    // The daemon destroys the socket mid-upload; either a 413 or a reset is acceptable.
    if (response) assert.equal(response.status, 413);
    assert.ok(!fs.existsSync(outPath));
  });
});

test('unknown routes 404', async () => {
  await withDaemon(async ({url}) => {
    const response = await fetch(`${url}/whatever`);
    assert.equal(response.status, 404);
  });
});
