/**
 * Regenerates src/colors-table.ts from the stable @airtable/blocks
 * devDependency (repo root). The table is committed so the built package
 * never imports the SDK — that is what keeps components Airtable-native
 * without SDK module imports (see plan/AIRGEN_UI_PLAN.md §2).
 *
 * Run from packages/ui: `npm run gen:colors`
 */
import {createRequire} from 'node:module';
import {writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';

const require = createRequire(import.meta.url);
const colors = require('@airtable/blocks/dist/cjs/colors.js').default;
const colorUtils = require('@airtable/blocks/dist/cjs/color_utils.js').default;

const names = Object.values(colors).sort();
const rows = names.map(name => {
  const hex = colorUtils.getHexForColor(name);
  const light = colorUtils.shouldUseLightTextOnColor(name);
  return `  ${JSON.stringify(name)}: ['${hex}', ${light}],`;
});

const sdkVersion = require('@airtable/blocks/package.json').version;

const out = `// Generated by scripts/gen-colors.mjs from @airtable/blocks ${sdkVersion} — do not edit by hand.

/** Airtable color name → [hex, use light text]. */
export const AIRTABLE_COLORS: {readonly [name: string]: readonly [string, boolean]} = {
${rows.join('\n')}
};
`;

const target = path.join(path.dirname(fileURLToPath(import.meta.url)), '../src/colors-table.ts');
writeFileSync(target, out);
console.log(`Wrote ${names.length} colors to ${path.relative(process.cwd(), target)}`);
