/**
 * airgen local schema daemon.
 *
 * Zero-dependency node:http listener the SchemaObserver extension component
 * POSTs generated TypeScript to. Security posture (deliberate — any webpage
 * can fire blind cross-origin POSTs at localhost):
 *   - binds 127.0.0.1 only
 *   - output path is fixed at startup; client-supplied paths are ignored
 *   - payload must be a bounded string starting with the airgen header
 */

import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';

const MAX_BODY_BYTES = 2 * 1024 * 1024;
const REQUIRED_HEADER = '// Generated by airgen';

function timestamp() {
  return new Date().toTimeString().slice(0, 8);
}

function setCorsHeaders(res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
}

function sendJson(res, status, body) {
  res.writeHead(status, {'Content-Type': 'application/json'});
  res.end(JSON.stringify(body));
}

function readBody(req, maxBytes) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let total = 0;
    req.on('data', chunk => {
      total += chunk.length;
      if (total > maxBytes) {
        reject(Object.assign(new Error('payload too large'), {statusCode: 413}));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', reject);
  });
}

/**
 * @param {{port?: number, host?: string, outPath?: string, log?: (msg: string) => void}} [options]
 * @returns {Promise<import('node:http').Server>}
 */
export function startDaemon({
  port = 3001,
  host = '127.0.0.1',
  outPath = './airtable-schema.ts',
  log = message => console.log(message),
} = {}) {
  const resolvedOut = path.resolve(process.cwd(), outPath);

  const server = http.createServer(async (req, res) => {
    setCorsHeaders(res);
    const url = new URL(req.url ?? '/', `http://${req.headers.host ?? 'localhost'}`);

    if (req.method === 'OPTIONS') {
      res.writeHead(204);
      res.end();
      return;
    }

    if (req.method === 'GET' && url.pathname === '/health') {
      res.writeHead(204);
      res.end();
      return;
    }

    if (req.method === 'POST' && url.pathname === '/save-schema') {
      try {
        const raw = await readBody(req, MAX_BODY_BYTES);
        let payload;
        try {
          payload = JSON.parse(raw);
        } catch {
          sendJson(res, 400, {error: 'body must be JSON'});
          return;
        }
        if (typeof payload?.code !== 'string' || !payload.code.startsWith(REQUIRED_HEADER)) {
          sendJson(res, 400, {error: 'code must be a string starting with the airgen header'});
          return;
        }
        if (payload.filePath !== undefined) {
          log(`[${timestamp()}] Ignoring client-supplied filePath (output path is fixed at startup)`);
        }

        const tableCount = typeof payload.tableCount === 'number' ? payload.tableCount : null;
        const suffix = tableCount !== null ? ` (${tableCount} table${tableCount === 1 ? '' : 's'})` : '';

        let existing = null;
        try {
          existing = fs.readFileSync(resolvedOut, 'utf8');
        } catch {
          // no existing file — first write
        }

        if (existing === payload.code) {
          log(`[${timestamp()}] Schema unchanged, skipped write${suffix}`);
          sendJson(res, 200, {ok: true, written: false});
          return;
        }

        fs.writeFileSync(resolvedOut, payload.code, 'utf8');
        log(`[${timestamp()}] Updated ${path.relative(process.cwd(), resolvedOut)}${suffix}`);
        sendJson(res, 200, {ok: true, written: true});
      } catch (error) {
        const status = error?.statusCode ?? 500;
        sendJson(res, status, {error: error?.message ?? 'internal error'});
      }
      return;
    }

    sendJson(res, 404, {error: 'not found'});
  });

  return new Promise((resolve, reject) => {
    server.once('error', reject);
    server.listen(port, host, () => {
      const address = server.address();
      log(`[${timestamp()}] airgen daemon listening on http://${host}:${address.port}`);
      log(`[${timestamp()}] Writing schema to ${resolvedOut}`);
      resolve(server);
    });
  });
}
