/**
 * airgen local schema daemon.
 *
 * Zero-dependency node:http listener the SchemaObserver extension component
 * POSTs generated TypeScript to. Security posture (deliberate — any webpage
 * can fire blind cross-origin POSTs at localhost):
 *   - binds 127.0.0.1 only
 *   - output path is fixed at startup; client-supplied paths are ignored
 *   - payload must be a bounded string starting with the airgen header
 */

import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';

import {createTypechecker} from './typecheck.js';
import {createCodemod} from './codemod.js';

const MAX_BODY_BYTES = 2 * 1024 * 1024;
/** /apply-fix carries only an id — no reason to accept more than that. */
const MAX_ID_BODY_BYTES = 4 * 1024;
const REQUIRED_HEADER = '// Generated by airgen';

function timestamp() {
  return new Date().toTimeString().slice(0, 8);
}

function setCorsHeaders(res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
}

function sendJson(res, status, body) {
  res.writeHead(status, {'Content-Type': 'application/json'});
  res.end(JSON.stringify(body));
}

function readBody(req, maxBytes) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let total = 0;
    req.on('data', chunk => {
      total += chunk.length;
      if (total > maxBytes) {
        reject(Object.assign(new Error('payload too large'), {statusCode: 413}));
        req.destroy();
        return;
      }
      chunks.push(chunk);
    });
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', reject);
  });
}

/**
 * @param {{port?: number, host?: string, outPath?: string, cwd?: string, fix?: boolean, log?: (msg: string) => void}} [options]
 * @returns {Promise<import('node:http').Server>}
 */
export function startDaemon({
  port = 3001,
  host = '127.0.0.1',
  outPath = './frontend/airtable-schema.ts',
  cwd = process.cwd(),
  fix = false,
  log = message => console.log(message),
} = {}) {
  const resolvedOut = path.resolve(cwd, outPath);
  fs.mkdirSync(path.dirname(resolvedOut), {recursive: true});

  const stamped = message => log(`[${timestamp()}] ${message}`);

  const typechecker = createTypechecker({
    cwd,
    startDir: path.dirname(resolvedOut),
    log: stamped,
  });

  // Opt-in only: without --fix the endpoints below 404 and no analysis runs,
  // so the daemon never writes outside its fixed output path.
  const codemod = fix ? createCodemod({cwd, outPath, log: stamped}) : null;

  const server = http.createServer(async (req, res) => {
    setCorsHeaders(res);
    const url = new URL(req.url ?? '/', `http://${req.headers.host ?? 'localhost'}`);

    if (req.method === 'OPTIONS') {
      res.writeHead(204);
      res.end();
      return;
    }

    if (req.method === 'GET' && url.pathname === '/health') {
      res.writeHead(204);
      res.end();
      return;
    }

    // A pure state read: any webpage can GET this (permissive CORS), so it
    // must never trigger a check, and its paths/messages are cwd-relative.
    if (req.method === 'GET' && url.pathname === '/diagnostics') {
      sendJson(res, 200, typechecker.current);
      return;
    }

    // Also a pure state read; 404 when --fix is off so the observer can
    // feature-detect and show nothing.
    if (req.method === 'GET' && url.pathname === '/fixes') {
      if (!codemod) {
        sendJson(res, 404, {error: 'assisted fixes are off (start airgen with --fix)'});
        return;
      }
      sendJson(res, 200, codemod.list());
      return;
    }

    // The request carries an id and nothing else — the edits applied are the
    // ones this daemon computed itself.
    if (req.method === 'POST' && url.pathname === '/apply-fix') {
      if (!codemod) {
        sendJson(res, 404, {error: 'assisted fixes are off (start airgen with --fix)'});
        return;
      }
      try {
        const raw = await readBody(req, MAX_ID_BODY_BYTES);
        let payload;
        try {
          payload = JSON.parse(raw);
        } catch {
          sendJson(res, 400, {error: 'body must be JSON'});
          return;
        }

        const result = codemod.apply({id: payload?.id, all: payload?.all});
        if (!result.ok) {
          sendJson(res, result.status, {error: result.error});
          return;
        }

        // Re-check so the panel confirms the fix landed clean.
        typechecker.schedule();
        sendJson(res, 200, {ok: true, files: result.files, invalidated: result.invalidated});
      } catch (error) {
        sendJson(res, error?.statusCode ?? 500, {error: error?.message ?? 'internal error'});
      }
      return;
    }

    if (req.method === 'POST' && url.pathname === '/save-schema') {
      try {
        const raw = await readBody(req, MAX_BODY_BYTES);
        let payload;
        try {
          payload = JSON.parse(raw);
        } catch {
          sendJson(res, 400, {error: 'body must be JSON'});
          return;
        }
        if (typeof payload?.code !== 'string' || !payload.code.startsWith(REQUIRED_HEADER)) {
          sendJson(res, 400, {error: 'code must be a string starting with the airgen header'});
          return;
        }
        if (payload.filePath !== undefined) {
          log(`[${timestamp()}] Ignoring client-supplied filePath (output path is fixed at startup)`);
        }

        const tableCount = typeof payload.tableCount === 'number' ? payload.tableCount : null;
        const suffix = tableCount !== null ? ` (${tableCount} table${tableCount === 1 ? '' : 's'})` : '';

        let existing = null;
        try {
          existing = fs.readFileSync(resolvedOut, 'utf8');
        } catch {
          // no existing file — first write
        }

        if (existing === payload.code) {
          log(`[${timestamp()}] Schema unchanged, skipped write${suffix}`);
          sendJson(res, 200, {ok: true, written: false});
          return;
        }

        fs.writeFileSync(resolvedOut, payload.code, 'utf8');
        log(`[${timestamp()}] Updated ${path.relative(cwd, resolvedOut)}${suffix}`);
        typechecker.schedule();
        // Needs the text from *before* this write to resolve the old symbols.
        if (codemod && existing !== null) codemod.schedule(existing, payload.code);
        sendJson(res, 200, {ok: true, written: true});
      } catch (error) {
        const status = error?.statusCode ?? 500;
        sendJson(res, status, {error: error?.message ?? 'internal error'});
      }
      return;
    }

    sendJson(res, 404, {error: 'not found'});
  });

  server.on('close', () => typechecker.dispose());

  return new Promise((resolve, reject) => {
    server.once('error', reject);
    server.listen(port, host, () => {
      const address = server.address();
      log(`[${timestamp()}] airgen daemon listening on http://${host}:${address.port}`);
      log(`[${timestamp()}] Will write schema to ${resolvedOut} (waiting for <SchemaObserver /> to connect)`);
      typechecker.schedule();
      resolve(server);
    });
  });
}
