/**
 * Pure schema → TypeScript source generator.
 *
 * Written against structural `BaseLike` types (not SDK classes) so it can run
 * against a real `Base` from `@airtable/blocks/models` inside the extension
 * AND against plain fixture objects in Node tests.
 *
 * Generated value types mirror what `record.getCellValue(field)` returns in
 * the Blocks SDK (rich shapes: select choices carry id/name/color, record
 * links are {id, name}[], collaborators have email/avatar) — NOT the flatter
 * REST API shapes.
 */

import {computeSchemaSignature} from './schema-signature.js';

export interface FieldLike {
  id: string;
  name: string;
  type: string;
  description?: string | null;
  options?: {[key: string]: unknown} | null;
}

export interface TableLike {
  id: string;
  name: string;
  description?: string | null;
  fields: ReadonlyArray<FieldLike>;
}

export interface BaseLike {
  id: string;
  name?: string;
  tables: ReadonlyArray<TableLike>;
}

/** First line of every generated file; the daemon refuses payloads without it. */
export const GENERATED_HEADER = '// Generated by airgen — do not edit.';

const SHARED_TYPES = `export interface Thumbnail {
  url: string;
  width: number;
  height: number;
}

export interface Attachment {
  id: string;
  url: string;
  filename: string;
  size?: number;
  type?: string;
  thumbnails?: {
    small?: Thumbnail;
    large?: Thumbnail;
    full?: Thumbnail;
  };
}

export interface Collaborator {
  id: string;
  email?: string;
  name?: string;
  profilePicUrl?: string;
}

export interface LinkedRecord {
  id: string;
  name: string;
}

export interface SelectChoice {
  id: string;
  name: string;
  color?: string;
}`;

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function quoteKey(name: string): string {
  return IDENTIFIER_RE.test(name) ? name : JSON.stringify(name);
}

const NON_DECOMPOSABLE: {[ch: string]: string} = {
  'ß': 'ss', 'ẞ': 'SS', 'æ': 'ae', 'Æ': 'AE', 'œ': 'oe', 'Œ': 'OE',
  'ø': 'o', 'Ø': 'O', 'đ': 'd', 'Đ': 'D', 'ð': 'd', 'Ð': 'D',
  'þ': 'th', 'Þ': 'Th', 'ł': 'l', 'Ł': 'L',
};

/** Latin transliteration: replace non-decomposable chars, then strip combining marks (ç→c, á→a, ê→e). */
function deaccent(name: string): string {
  return name
    .replace(/[ßẞæÆœŒøØđĐðÐþÞłŁ]/g, ch => NON_DECOMPOSABLE[ch])
    .normalize('NFD')
    .replace(/\p{M}/gu, '');
}

function splitWords(name: string): string[] {
  return deaccent(name)
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean);
}

/** ALL-CAPS words fold their body ("ID" → "Id"); mixed-case bodies are preserved. */
function pascalWord(word: string): string {
  const body = /^[A-Z0-9]+$/.test(word) ? word.toLowerCase() : word;
  return body.charAt(0).toUpperCase() + body.slice(1);
}

function pascalCase(name: string): string {
  let result = splitWords(name).map(pascalWord).join('');

  if (result === '') result = 'Table';
  if (/^[0-9]/.test(result)) result = 'T' + result;

  return result;
}

/** Returns '' when no words survive sanitization (e.g. emoji-only names) — callers fall back to the raw name. */
function camelCase(name: string): string {
  const words = splitWords(name);

  if (words.length === 0) return '';

  const first = /^[A-Z0-9]+$/.test(words[0])
    ? words[0].toLowerCase()
    : words[0].charAt(0).toLowerCase() + words[0].slice(1);

  let result = first + words.slice(1).map(pascalWord).join('');

  if (/^[0-9]/.test(result)) result = '_' + result;
  return result;
}

/** Assigns collision-free keys, appending 2, 3, … on clashes. */
function uniqueNames<T>(items: ReadonlyArray<T>, toName: (item: T) => string): Map<T, string> {
  const used = new Set<string>();
  const assigned = new Map<T, string>();

  for (const item of items) {
    const baseName = toName(item);
    let candidate = baseName;
    let suffix = 2;

    while (used.has(candidate)) {
      candidate = `${baseName}${suffix}`;
      suffix++;
    }

    used.add(candidate);
    assigned.set(item, candidate);
  }

  return assigned;
}

interface ChoiceOption {
  id: string;
  name: string;
  color?: string;
}

function selectChoices(options: FieldLike['options']): ChoiceOption[] | null {
  if (!options || !Array.isArray(options.choices)) return null;

  const choices: ChoiceOption[] = [];

  for (const raw of options.choices as Array<{id?: unknown; name?: unknown; color?: unknown}>) {
    if (typeof raw?.id !== 'string' || typeof raw?.name !== 'string') continue;
    choices.push({id: raw.id, name: raw.name, color: typeof raw.color === 'string' ? raw.color : undefined});
  }

  return choices.length > 0 ? choices : null;
}

function choiceUnion(choices: ChoiceOption[]): string {
  return choices
    .map(choice => `{ id: ${JSON.stringify(choice.id)}; name: ${JSON.stringify(choice.name)}; color?: string }`)
    .join(' | ');
}

interface ResolvedType {
  ts: string;
  comment?: string;
}

/** How far `options.result` nesting is followed (formula of rollup of lookup…). */
const MAX_RESULT_DEPTH = 3;

/** Field types whose value type comes from `options.result`. */
const COMPUTED_TYPES = new Set(['formula', 'rollup', 'multipleLookupValues']);

/**
 * Maps an Airtable field type (FieldType enum string values from
 * `@airtable/blocks/models`) to the TS type of its `getCellValue` result.
 * `selectAlias` is the pre-registered alias name for this field's choice
 * union, when the field is a select with known choices.
 */
function resolveFieldType(
  type: string,
  options: FieldLike['options'],
  selectAlias: string | null,
  depth: number,
): ResolvedType {
  switch (type) {
    case 'singleLineText':
    case 'multilineText':
    case 'richText':
    case 'email':
    case 'url':
    case 'phoneNumber':
      return {ts: 'string'};

    case 'date':
    case 'dateTime':
    case 'createdTime':
    case 'lastModifiedTime':
      return {ts: 'string'};

    case 'number':
    case 'percent':
    case 'currency':
    case 'rating':
    case 'duration':
    case 'count':
    case 'autoNumber':
      return {ts: 'number'};

    case 'checkbox':
      return {ts: 'boolean'};

    case 'singleSelect': {
      if (selectAlias) return {ts: selectAlias};
      const choices = selectChoices(options);

      return {ts: choices ? choiceUnion(choices) : 'SelectChoice'};
    }
    case 'multipleSelects': {
      if (selectAlias) return {ts: `${selectAlias}[]`};
      const choices = selectChoices(options);

      return {ts: choices ? `Array<${choiceUnion(choices)}>` : 'SelectChoice[]'};
    }
    case 'multipleRecordLinks':
      return {ts: 'LinkedRecord[]'};

    case 'multipleAttachments':
      return {ts: 'Attachment[]'};

    case 'singleCollaborator':
    case 'createdBy':
    case 'lastModifiedBy':
      return {ts: 'Collaborator'};

    case 'multipleCollaborators':
      return {ts: 'Collaborator[]'};

    case 'barcode':
      return {ts: '{ text: string; type?: string }'};

    case 'button':
      return {ts: '{ label: string; url: string | null }'};

    case 'formula':
    case 'rollup': {
      const result = resolveResultType(options, depth);
      return result ?? {ts: 'unknown', comment: `${type} without a known result type`};
    }

    case 'multipleLookupValues': {
      const result = resolveResultType(options, depth);
      return result ? {ts: `Array<${result.ts}>`} : {ts: 'unknown[]', comment: 'lookup without a known result type'};
    }

    default:
      return {ts: 'unknown', comment: `unmapped: ${type}`};
  }
}

interface ResultFieldConfig {
  type: string;
  options: {[key: string]: unknown} | null;
}

/**
 * `options.result`, as far as the generator reads it. In the SDK this is a
 * full `FieldConfig` (see field_core.ts), so it nests: a lookup of a select
 * carries that select's `choices` here.
 */
function resultFieldConfig(options: FieldLike['options']): ResultFieldConfig | null {
  if (!options || !options.result || typeof options.result !== 'object') return null;
  const result = options.result as {type?: unknown; options?: unknown};
  if (typeof result.type !== 'string') return null;
  return {
    type: result.type,
    options: result.options && typeof result.options === 'object' ? (result.options as {[key: string]: unknown}) : null,
  };
}

/** Formula/rollup/lookup expose their computed type via options.result. */
function resolveResultType(options: FieldLike['options'], depth: number): ResolvedType | null {
  if (depth > MAX_RESULT_DEPTH) return null;
  const result = resultFieldConfig(options);
  if (!result) return null;
  return resolveFieldType(result.type, result.options, null, depth + 1);
}

export interface ChoiceMeta {
  id: string;
  name: string;
  color?: string;
}

/** Recursive mirror of `options.result` — same shape as FieldTypeMeta plus its type. */
export interface ResultMeta extends FieldTypeMeta {
  type: string;
}

/**
 * The part of a field's `options` that changes the *generated type* — exactly
 * what `resolveFieldType` reads — plus choice `color`, carried for UI
 * consumers of the meta. Color never changes the emitted type (`choiceUnion`
 * emits `color?: string`, not a literal) and stays invisible to drift and the
 * codemod diff, which compare choices by id/name only.
 */
export interface FieldTypeMeta {
  choices?: ChoiceMeta[];
  result?: ResultMeta;
}

export interface FieldMeta extends FieldTypeMeta {
  id: string;
  name: string;
  type: string;
}

/**
 * Projects a field's options down to what affects its emitted type. This is
 * the single source of truth behind the three-way coupling in CLAUDE.md:
 * whatever `resolveFieldType` starts reading must show up here too, or
 * `buildAirgenMeta` bakes in a stale picture and `checkSchemaDrift` goes blind
 * to that class of change.
 */
export function buildFieldTypeMeta(
  type: string,
  options: FieldLike['options'],
  depth = 0,
): FieldTypeMeta {
  const meta: FieldTypeMeta = {};

  if (type === 'singleSelect' || type === 'multipleSelects') {
    const choices = selectChoices(options);
    // Spread color conditionally: a colorless choice must not carry an own
    // `color: undefined` key, so the in-memory shape matches the emitted JSON.
    if (choices) {
      meta.choices = choices.map(choice => ({
        id: choice.id,
        name: choice.name,
        ...(choice.color !== undefined && {color: choice.color}),
      }));
    }
  }

  if (COMPUTED_TYPES.has(type) && depth <= MAX_RESULT_DEPTH) {
    const result = resultFieldConfig(options);
    if (result) {
      meta.result = {type: result.type, ...buildFieldTypeMeta(result.type, result.options, depth + 1)};
    }
  }

  return meta;
}

export interface TableMeta {
  id: string;
  name: string;
  fields: {[fieldKey: string]: FieldMeta};
}

export interface GeneratedMeta {
  /** Meta format version; bump when the shape changes incompatibly. */
  version: number;
  baseId: string;
  signature: string;
  tables: {[tableKey: string]: TableMeta};
}

interface FieldPlan {
  field: FieldLike;
  /** Sanitized property key, deduped within its table. */
  key: string;
}

interface TablePlan {
  table: TableLike;
  /** Sanitized table key, deduped across the base. */
  key: string;
  interfaceName: string;
  fields: FieldPlan[];
}

/**
 * Assigns every sanitized name the file will use, once.
 *
 * The meta and the emitted interfaces MUST agree on these keys — the runtime
 * builds `record.fields` from the meta keys — so both are derived from this one
 * plan rather than from two parallel `uniqueNames` calls that could drift.
 */
function planTables(base: BaseLike): TablePlan[] {
  const tableKeys = uniqueNames(base.tables, table => pascalCase(table.name));

  return base.tables.map(table => {
    // camelCase is lossy ("Soluções" and "Solucoes" both → solucoes), so dedup
    // per table; '' falls back to the raw name, which quoteKey will quote.
    const fieldKeys = uniqueNames(table.fields, field => camelCase(field.name) || field.name);
    const key = tableKeys.get(table)!;

    return {
      table,
      key,
      interfaceName: `${key}Record`,
      fields: table.fields.map(field => ({field, key: fieldKeys.get(field)!})),
    };
  });
}

function buildMetaFromPlan(base: BaseLike, plan: ReadonlyArray<TablePlan>): GeneratedMeta {
  const tables: {[tableKey: string]: TableMeta} = {};

  for (const {table, key, fields} of plan) {
    const fieldMetas: {[fieldKey: string]: FieldMeta} = {};

    for (const {field, key: fieldKey} of fields) {
      fieldMetas[fieldKey] = {
        id: field.id,
        name: field.name,
        type: field.type,
        ...buildFieldTypeMeta(field.type, field.options ?? null),
      };
    }

    tables[key] = {id: table.id, name: table.name, fields: fieldMetas};
  }

  // No timestamp or other nondeterminism: the same schema must generate
  // byte-identical output, or the daemon's content dedup can't break the
  // write → hot-reload → remount → regenerate cycle.
  return {
    version: 1,
    baseId: base.id,
    signature: computeSchemaSignature(base),
    tables,
  };
}

/**
 * The `airgenMeta` object a generated file bakes in, as a plain value. The
 * generator embeds exactly this (JSON.stringify'd); tests and drift checks use
 * it directly.
 */
export function buildAirgenMeta(base: BaseLike): GeneratedMeta {
  return buildMetaFromPlan(base, planTables(base));
}

export interface GeneratorOptions {
  /**
   * Module specifier the generated file imports `createTypedHooks` from.
   * Override when airgen is re-exported under a different name (monorepo
   * alias, vendored copy).
   */
  hooksModule?: string;
}

/**
 * Hands out choice alias names. Aliases are file-global (two tables can both
 * have a "Status" select), so collisions get a numeric suffix.
 */
function createAliasRegistry() {
  const used = new Set<string>();

  return function registerAlias(tableKey: string, fieldName: string): string {
    const baseName = `${tableKey}${pascalCase(fieldName)}Choice`;
    let candidate = baseName;
    let suffix = 2;

    while (used.has(candidate)) {
      candidate = `${baseName}${suffix}`;
      suffix++;
    }

    used.add(candidate);
    return candidate;
  };
}

/**
 * NOTE: `schema-diff.js` reads this doc comment back to detect alias renames.
 * Keep the `choices of <field> in table <table>` wording in step with the
 * regex there.
 */
function aliasDeclaration(alias: string, table: TableLike, field: FieldLike, choices: ChoiceOption[]): string {
  return `/** choices of ${JSON.stringify(field.name)} in table ${JSON.stringify(table.name)} */\nexport type ${alias} = ${choiceUnion(choices)};`;
}

/** The `/** … *​/` line above a property, or null when there's nothing to say. */
function fieldDocLine(fieldKey: string, field: FieldLike, resolved: ResolvedType): string | null {
  const parts: string[] = [];

  if (fieldKey !== field.name) parts.push(`Airtable field ${JSON.stringify(field.name)}`);
  if (field.description) parts.push(field.description.trim());
  if (resolved.comment) parts.push(resolved.comment);

  if (parts.length === 0) return null;
  return `  /** ${parts.join(' — ').replace(/\*\//g, '*\\/')} */`;
}

interface TableEmission {
  /** Alias declarations this table contributed, in field order. */
  aliases: string[];
  recordInterface: string;
  recordMapEntry: string;
}

function emitTable(plan: TablePlan, registerAlias: ReturnType<typeof createAliasRegistry>): TableEmission {
  const {table, key: tableKey, interfaceName, fields} = plan;
  const aliases: string[] = [];
  const lines: string[] = [];

  for (const {field, key: fieldKey} of fields) {
    // Selects with known choices get a named alias so consumers can refer to
    // the union by name instead of restating it.
    const isSelect = field.type === 'singleSelect' || field.type === 'multipleSelects';
    const choices = isSelect ? selectChoices(field.options) : null;
    let selectAlias: string | null = null;

    if (choices) {
      selectAlias = registerAlias(tableKey, field.name);
      aliases.push(aliasDeclaration(selectAlias, table, field, choices));
    }

    const resolved = resolveFieldType(field.type, field.options ?? null, selectAlias, 0);
    const doc = fieldDocLine(fieldKey, field, resolved);

    if (doc !== null) lines.push(doc);
    lines.push(`  ${quoteKey(fieldKey)}?: ${resolved.ts};`);
  }

  return {
    aliases,
    recordInterface: `/** table ${JSON.stringify(table.name)} (${table.id}) */\nexport interface ${interfaceName} {\n${lines.join('\n')}\n}`,
    recordMapEntry: `  ${quoteKey(tableKey)}: ${interfaceName};`,
  };
}

function fileHeader(base: BaseLike, signature: string): string {
  const name = base.name ? ` (${base.name})` : '';
  return `${GENERATED_HEADER}\n// Base: ${base.id}${name}\n// Signature: ${signature}\n/* eslint-disable */`;
}

export function generateTypeScriptFromBase(base: BaseLike, options: GeneratorOptions = {}): string {
  const hooksModule = options.hooksModule ?? 'airgen';
  const plan = planTables(base);
  const meta = buildMetaFromPlan(base, plan);

  const registerAlias = createAliasRegistry();
  const emissions = plan.map(tablePlan => emitTable(tablePlan, registerAlias));

  const sections = [
    fileHeader(base, meta.signature),
    `import {createTypedHooks} from '${hooksModule.replace(/'/g, "\\'")}';`,
    SHARED_TYPES,
    ...emissions.flatMap(emission => emission.aliases),
    ...emissions.map(emission => emission.recordInterface),
    `export const airgenMeta = ${JSON.stringify(meta, null, 2)} as const;`,
    `export interface TableRecordMap {\n${emissions.map(emission => emission.recordMapEntry).join('\n')}\n}\n\nexport type TableKey = keyof TableRecordMap;`,
    `export const {useRecords, useTable, useSchemaDrift} = createTypedHooks<TableRecordMap>(airgenMeta);`,
  ];

  return sections.join('\n\n') + '\n';
}
