/**
 * Pure schema → TypeScript source generator.
 *
 * Written against structural `BaseLike` types (not SDK classes) so it can run
 * against a real `Base` from `@airtable/blocks/models` inside the extension
 * AND against plain fixture objects in Node tests.
 *
 * Generated value types mirror what `record.getCellValue(field)` returns in
 * the Blocks SDK (rich shapes: select choices carry id/name/color, record
 * links are {id, name}[], collaborators have email/avatar) — NOT the flatter
 * REST API shapes.
 */

import {computeSchemaSignature} from './schema-signature.js';

export interface FieldLike {
  id: string;
  name: string;
  type: string;
  description?: string | null;
  options?: {[key: string]: unknown} | null;
}

export interface TableLike {
  id: string;
  name: string;
  description?: string | null;
  fields: ReadonlyArray<FieldLike>;
}

export interface BaseLike {
  id: string;
  name?: string;
  tables: ReadonlyArray<TableLike>;
}

/** First line of every generated file; the daemon refuses payloads without it. */
export const GENERATED_HEADER = '// Generated by airgen — do not edit.';

const SHARED_TYPES = `export interface Thumbnail {
  url: string;
  width: number;
  height: number;
}

export interface Attachment {
  id: string;
  url: string;
  filename: string;
  size?: number;
  type?: string;
  thumbnails?: {
    small?: Thumbnail;
    large?: Thumbnail;
    full?: Thumbnail;
  };
}

export interface Collaborator {
  id: string;
  email?: string;
  name?: string;
  profilePicUrl?: string;
}

export interface LinkedRecord {
  id: string;
  name: string;
}

export interface SelectChoice {
  id: string;
  name: string;
  color?: string;
}`;

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function quoteKey(name: string): string {
  return IDENTIFIER_RE.test(name) ? name : JSON.stringify(name);
}

const NON_DECOMPOSABLE: {[ch: string]: string} = {
  'ß': 'ss', 'ẞ': 'SS', 'æ': 'ae', 'Æ': 'AE', 'œ': 'oe', 'Œ': 'OE',
  'ø': 'o', 'Ø': 'O', 'đ': 'd', 'Đ': 'D', 'ð': 'd', 'Ð': 'D',
  'þ': 'th', 'Þ': 'Th', 'ł': 'l', 'Ł': 'L',
};

/** Latin transliteration: replace non-decomposable chars, then strip combining marks (ç→c, á→a, ê→e). */
function deaccent(name: string): string {
  return name
    .replace(/[ßẞæÆœŒøØđĐðÐþÞłŁ]/g, ch => NON_DECOMPOSABLE[ch])
    .normalize('NFD')
    .replace(/\p{M}/gu, '');
}

function splitWords(name: string): string[] {
  return deaccent(name)
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean);
}

/** ALL-CAPS words fold their body ("ID" → "Id"); mixed-case bodies are preserved. */
function pascalWord(word: string): string {
  const body = /^[A-Z0-9]+$/.test(word) ? word.toLowerCase() : word;
  return body.charAt(0).toUpperCase() + body.slice(1);
}

function pascalCase(name: string): string {
  let result = splitWords(name).map(pascalWord).join('');
  if (result === '') result = 'Table';
  if (/^[0-9]/.test(result)) result = 'T' + result;
  return result;
}

/** Returns '' when no words survive sanitization (e.g. emoji-only names) — callers fall back to the raw name. */
function camelCase(name: string): string {
  const words = splitWords(name);
  if (words.length === 0) return '';
  const first = /^[A-Z0-9]+$/.test(words[0])
    ? words[0].toLowerCase()
    : words[0].charAt(0).toLowerCase() + words[0].slice(1);
  let result = first + words.slice(1).map(pascalWord).join('');
  if (/^[0-9]/.test(result)) result = '_' + result;
  return result;
}

/** Assigns collision-free keys, appending 2, 3, … on clashes. */
function uniqueNames<T>(items: ReadonlyArray<T>, toName: (item: T) => string): Map<T, string> {
  const used = new Set<string>();
  const assigned = new Map<T, string>();
  for (const item of items) {
    const baseName = toName(item);
    let candidate = baseName;
    let suffix = 2;
    while (used.has(candidate)) {
      candidate = `${baseName}${suffix}`;
      suffix++;
    }
    used.add(candidate);
    assigned.set(item, candidate);
  }
  return assigned;
}

interface ChoiceOption {
  id: string;
  name: string;
  color?: string;
}

function selectChoices(options: FieldLike['options']): ChoiceOption[] | null {
  if (!options || !Array.isArray(options.choices)) return null;
  const choices: ChoiceOption[] = [];
  for (const raw of options.choices as Array<{id?: unknown; name?: unknown; color?: unknown}>) {
    if (typeof raw?.id !== 'string' || typeof raw?.name !== 'string') continue;
    choices.push({id: raw.id, name: raw.name, color: typeof raw.color === 'string' ? raw.color : undefined});
  }
  return choices.length > 0 ? choices : null;
}

function choiceUnion(choices: ChoiceOption[]): string {
  return choices
    .map(choice => `{ id: ${JSON.stringify(choice.id)}; name: ${JSON.stringify(choice.name)}; color?: string }`)
    .join(' | ');
}

interface ResolvedType {
  ts: string;
  comment?: string;
}

/**
 * Maps an Airtable field type (FieldType enum string values from
 * `@airtable/blocks/models`) to the TS type of its `getCellValue` result.
 * `selectAlias` is the pre-registered alias name for this field's choice
 * union, when the field is a select with known choices.
 */
function resolveFieldType(
  type: string,
  options: FieldLike['options'],
  selectAlias: string | null,
  depth: number,
): ResolvedType {
  switch (type) {
    case 'singleLineText':
    case 'multilineText':
    case 'richText':
    case 'email':
    case 'url':
    case 'phoneNumber':
      return {ts: 'string'};
    case 'date':
    case 'dateTime':
    case 'createdTime':
    case 'lastModifiedTime':
      return {ts: 'string'};
    case 'number':
    case 'percent':
    case 'currency':
    case 'rating':
    case 'duration':
    case 'count':
    case 'autoNumber':
      return {ts: 'number'};
    case 'checkbox':
      return {ts: 'boolean'};
    case 'singleSelect': {
      if (selectAlias) return {ts: selectAlias};
      const choices = selectChoices(options);
      return {ts: choices ? choiceUnion(choices) : 'SelectChoice'};
    }
    case 'multipleSelects': {
      if (selectAlias) return {ts: `${selectAlias}[]`};
      const choices = selectChoices(options);
      return {ts: choices ? `Array<${choiceUnion(choices)}>` : 'SelectChoice[]'};
    }
    case 'multipleRecordLinks':
      return {ts: 'LinkedRecord[]'};
    case 'multipleAttachments':
      return {ts: 'Attachment[]'};
    case 'singleCollaborator':
    case 'createdBy':
    case 'lastModifiedBy':
      return {ts: 'Collaborator'};
    case 'multipleCollaborators':
      return {ts: 'Collaborator[]'};
    case 'barcode':
      return {ts: '{ text: string; type?: string }'};
    case 'button':
      return {ts: '{ label: string; url: string | null }'};
    case 'formula':
    case 'rollup': {
      const result = resolveResultType(options, depth);
      return result ?? {ts: 'unknown', comment: `${type} without a known result type`};
    }
    case 'multipleLookupValues': {
      const result = resolveResultType(options, depth);
      return result ? {ts: `Array<${result.ts}>`} : {ts: 'unknown[]', comment: 'lookup without a known result type'};
    }
    default:
      return {ts: 'unknown', comment: `unmapped: ${type}`};
  }
}

/** Formula/rollup/lookup expose their computed type via options.result. */
function resolveResultType(options: FieldLike['options'], depth: number): ResolvedType | null {
  if (depth > 3) return null;
  if (!options || !options.result || typeof options.result !== 'object') return null;
  const result = options.result as {type?: unknown; options?: unknown};
  if (typeof result.type !== 'string') return null;
  const resultOptions =
    result.options && typeof result.options === 'object' ? (result.options as {[key: string]: unknown}) : null;
  return resolveFieldType(result.type, resultOptions, null, depth + 1);
}

interface FieldMeta {
  id: string;
  name: string;
  type: string;
  choices?: {[choiceName: string]: string};
}

export interface GeneratorOptions {
  /**
   * Module specifier the generated file imports `createTypedHooks` from.
   * Override when airgen is re-exported under a different name (monorepo
   * alias, vendored copy).
   */
  hooksModule?: string;
}

export function generateTypeScriptFromBase(base: BaseLike, options: GeneratorOptions = {}): string {
  const hooksModule = options.hooksModule ?? 'airgen';
  const signature = computeSchemaSignature(base);
  const tableNames = uniqueNames(base.tables, table => pascalCase(table.name));

  const aliasSections: string[] = [];
  const interfaceSections: string[] = [];
  const recordMapEntries: string[] = [];
  const metaTables: {[tableKey: string]: {id: string; name: string; fields: {[fieldName: string]: FieldMeta}}} = {};

  const usedAliasNames = new Set<string>();

  for (const table of base.tables) {
    const tableKey = tableNames.get(table)!;
    const interfaceName = `${tableKey}Record`;

    const fieldLines: string[] = [];
    const metaFields: {[fieldKey: string]: FieldMeta} = {};
    // camelCase is lossy ("Soluções" and "Solucoes" both → solucoes), so dedup
    // per table; '' falls back to the raw name, which quoteKey will quote.
    const fieldKeys = uniqueNames(table.fields, field => camelCase(field.name) || field.name);

    for (const field of table.fields) {
      const fieldKey = fieldKeys.get(field)!;
      // Register a named alias for select fields with known choices.
      let selectAlias: string | null = null;
      const isSelect = field.type === 'singleSelect' || field.type === 'multipleSelects';
      const choices = isSelect ? selectChoices(field.options) : null;
      if (choices) {
        let candidate = `${tableKey}${pascalCase(field.name)}Choice`;
        let suffix = 2;
        while (usedAliasNames.has(candidate)) {
          candidate = `${tableKey}${pascalCase(field.name)}Choice${suffix}`;
          suffix++;
        }
        usedAliasNames.add(candidate);
        selectAlias = candidate;
        aliasSections.push(`/** choices of ${JSON.stringify(field.name)} in table ${JSON.stringify(table.name)} */\nexport type ${candidate} = ${choiceUnion(choices)};`);
      }

      const resolved = resolveFieldType(field.type, field.options ?? null, selectAlias, 0);
      const docParts: string[] = [];
      if (fieldKey !== field.name) docParts.push(`Airtable field ${JSON.stringify(field.name)}`);
      if (field.description) docParts.push(field.description.trim());
      if (resolved.comment) docParts.push(resolved.comment);
      if (docParts.length > 0) {
        fieldLines.push(`  /** ${docParts.join(' — ').replace(/\*\//g, '*\\/')} */`);
      }
      fieldLines.push(`  ${quoteKey(fieldKey)}?: ${resolved.ts};`);

      const fieldMeta: FieldMeta = {id: field.id, name: field.name, type: field.type};
      if (choices) {
        fieldMeta.choices = {};
        for (const choice of choices) fieldMeta.choices[choice.name] = choice.id;
      }
      // Must be the same key as the interface property above — the runtime
      // builds record.fields from these meta keys (resolving by fieldMeta.id).
      metaFields[fieldKey] = fieldMeta;
    }

    interfaceSections.push(
      `/** table ${JSON.stringify(table.name)} (${table.id}) */\nexport interface ${interfaceName} {\n${fieldLines.join('\n')}\n}`,
    );
    recordMapEntries.push(`  ${quoteKey(tableKey)}: ${interfaceName};`);
    metaTables[tableKey] = {id: table.id, name: table.name, fields: metaFields};
  }

  const meta = {
    baseId: base.id,
    signature,
    generatedAt: new Date().toISOString(),
    tables: metaTables,
  };

  const sections = [
    `${GENERATED_HEADER}\n// Base: ${base.id}${base.name ? ` (${base.name})` : ''}\n// Signature: ${signature}\n/* eslint-disable */`,
    `import {createTypedHooks} from '${hooksModule.replace(/'/g, "\\'")}';`,
    SHARED_TYPES,
    ...aliasSections,
    ...interfaceSections,
    `export const airgenMeta = ${JSON.stringify(meta, null, 2)} as const;`,
    `export interface TableRecordMap {\n${recordMapEntries.join('\n')}\n}\n\nexport type TableKey = keyof TableRecordMap;`,
    `export const {useRecords, useTable} = createTypedHooks<TableRecordMap>(airgenMeta);`,
  ];

  return sections.join('\n\n') + '\n';
}
